package kr.rtustudio.donation.service.chzzk.net.http.executor;

public enum Requests {

    ACCESS_TOKEN_GRANT,
    ACCESS_TOKEN_REFRESH,
    ACCESS_TOKEN_REVOKE,
    AUTHORIZATION_CODE,
    CATEGORY_SEARCH,
    CHANNEL_INFORMATION,
    CHANNEL_MANAGER,
    CHANNEL_FOLLOWER,
    CHANNEL_SUBSCRIBER,
    CHAT_ANNOUNCEMENT_SET,
    CHAT_MESSAGE_SEND,
    CHAT_SETTINGS_CHANGE,
    CHAT_SETTINGS,
    LIVE_SEARCH,
    LIVE_SETTINGS_CHANGE,
    LIVE_SETTINGS,
    LIVE_STREAM_KEY,
    USER_INFORMATION,
    SESSION_URL,
    CHAT_EVENT_SUBSCRIBE,
    CHAT_EVENT_UNSUBSCRIBE,
    DONATION_EVENT_SUBSCRIBE,
    DONATION_EVENT_UNSUBSCRIBE,
    SESSION_SEARCH,
    RESTRICTION_ADD,
    RESTRICTION_DELETE,
    RESTRICTION_SEARCH

}
